Repository BF-FrontEnd-class-2025/group-1-all-about-trees, pull requests merged in 2025-01, with the labels that each got.

#2 add title for our project
  README.md
Labels: md

#4 add constraints
  planning/constraints.md
Labels: md

#6 add our communication
  .cspell.json
  planning/communication.md
Labels: md, planning

#8 add user-personas
  planning/user-personas.md
Labels: md

#11 fixed version of project definition
  README.md
Labels: md

#15 Constrains
  planning/constraints.md
Labels: md, planning

#9 add info-backlog
  planning/backlog.md
Labels: md, planning

#19 backlogv2
  planning/backlog.md
Labels: md

#16 add design
  planning/Untitled-2025-01-20-1022.png
  planning/design.md
Labels: md

#20 Update communication.md
  planning/communication.md
Labels: md

#24 update user-personas.md
  planning/user-personas.md
Labels: md

#28 Update design.md
  planning/design.md
Labels: md

#30 main README update
  README.md
  screenshot.png
Labels: md

#35 add developement-stategy
  planning/development-strategy.md
Labels: md

#43 Revert "Revert "updated html and css and image""
  index.html
  public/happy-tree.jpg
  styles/something.css
Labels: css, html

#44 restrospective
  planning/retrospective.md
Labels: md, planning
